type TCustomers = {
  Address: string;
  BirthDate: Date;
  CompanyName: string;
  ContactCustomerMappingRequests: Array;
  ContactCustomerSaleRequests: Array;
  ContactCustomerNotes: Array;
  CustomerName: string;
  Email: string;
  ExpectedMoney: number;
  FullName: string;
  Gender: boolean;
  JobDescription: string;
  ListFormUrl: string;
  ListSourceId: string;
  ParentCompanyId: number;
  Phone: number;
  RequestName: string;
  SaleId: number;
  SaleName: string;
  SaleReceiveDate: Date;
  SaleStatus: number;
  SaleStatusName: string;
  SourceIds: number;
  SourceName: string;
  Status: number;
  StatusName: string;
  TawkChatId: number;
  TawkMessagingId: number;
  TawkProperty: number;
  UserId: number;
  Active: boolean;
  Created: number;
  CreatedBy: string;
  Id: string;
  Updated: Date;
  UpdatedBy: string;
  LastName: string;
  FirstName: string;
  CustomerPosition: string;
};

type THistoryContact = {
  Id: string;
  Created: Date;
  Note: string;
  Description: string;
  RequestDescription: string;
};
