type TStaff = {
  Active: boolean;
  Address: string;
  Birthday: number;
  Created: number;
  CreatedBy: string;
  Email: string;
  ExpiredDate: number;
  FirstName: string;
  FullName: string;
  Gender: number;
  Id: string;
  LastName: string;
  Password: string;
  Phone: string;
  Roles: string;
  Status: number;
  Thumbnail: string;
  Token: string;
  Updated: number;
  UpdatedBy: string;
  Username: string;
  Roles: any;
};
